export { default as Header } from './header'
export { default as About } from './about'
export { default as Projects } from './project'
export { default as Contact } from './contact'
export { default as Footer } from './footer'
